# Generated by Django 3.2.8 on 2021-10-07 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fastfood.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.CharField(max_length=800, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='discount')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('image', models.ImageField(blank=True, default='food/default.png', null=True, upload_to=fastfood.models.upload_to, verbose_name='image')),
                ('like_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='fastfood.category', verbose_name='category')),
                ('likes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
                'db_table': 'food',
                'ordering': ['-published'],
            },
        ),
    ]
