# Generated by Django 3.2.8 on 2021-10-07 21:55

import django.core.validators
from django.db import migrations, models
import fastfood.models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, default='food/default.png', null=True, upload_to=fastfood.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'mp4', 'wmv', 'flv', 'png'))], verbose_name='image'),
        ),
    ]
